### ISSUE TITLE
Can load config form other place?

### ISSUE THREAD

**Issue by hengyunabc** [mybatis/ehcache-cache#20]
Can load config form other place?

How to use a existed ehcacheManager?

``` xml
    <bean id="ehcacheManager"
        class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean">
        <property name="configLocation" value="classpath:my-ehcache.xml" />
    </bean>
```

**Comment by hengyunabc** [comment]
I create this project to resolve my problem. :)
https://github.com/hengyunabc/mybatis-ehcache-spring

**Comment by hazendaz** [comment]
@hengyunabc I'm looking to push a release of ehcache-cache soon.  I see you had this issue out here for a little while now and it's gone unnoticed.  If this were to be brought into mybatis itself such that a user using it as-is doesn't notice any changes and those wanted to take advantage of the newer features could, would you be up for getting a PR to do such a thing?  Seems both your project and this project are so small that I think it doens't warrent haven't two separate overall projects so long as these are packaged properly, has all that documentation you already created, and potentially can get a running example as you noted on your own issues area.  Let me know what you think.

**Comment by hazendaz** [comment]
@hengyunabc I'm releasing a cut now without this.  If you would like this to get into the main core, plase submit a pull request and I can make a release shortly after.  Thanks, Jeremy.

**Comment by hengyunabc** [comment]
I'm sorry I do not have time to deal with this problem.  And my project is not good enough.

Thank you very much for your patience.

**Comment by hazendaz** [comment]
No worries.  If you do need this in the future, feel free to open a PR at that time.  Thanks.
