### ISSUE TITLE
download too slow in China

### ISSUE THREAD

**Issue by AsanZhang** [mybatis/ehcache-cache#35]
I am disheartened to see that downloading the jar is too slow in China!I can't wait for it,and I am going to mad!!! It remains the status :
![download too slow](http://asantoday0.oss-cn-qingdao.aliyuncs.com/forum/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-05-22%2018.11.29.png)

**Comment by emacarron** [comment]
Sorry to hear that. You may try getting the .jar from maven central instead.

**Comment by hazendaz** [comment]
You can find the jar [here](http://search.maven.org/remotecontent?filepath=org/mybatis/caches/mybatis-ehcache/1.0.3/mybatis-ehcache-1.0.3.jar).

Or latest snapshot [here](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/caches/mybatis-ehcache/1.1.0-SNAPSHOT/mybatis-ehcache-1.1.0-20160424.043046-59.jar)
