### ISSUE TITLE
mapper.xml 配置cache的时间无效

### ISSUE THREAD

**Issue by wengwh** [mybatis/ehcache-cache#54]
在ehcache.xml配置了默认的缓存信息，时间300s

在mapper.xml配置过期时间3s，测试结果，还是300s有效果

使用springboot 框架

**Comment by harawata** [comment]
I'm sorry, but please write in English.

And consider providing an executable test case or example project.
https://github.com/mybatis/mybatis-3/wiki/Unit-Test
https://github.com/harawata/mybatis-issues
