### ISSUE TITLE
Question - integrating Ehcache Monitor

### ISSUE THREAD

**Issue by n1zea144** [mybatis/ehcache-cache#56]
Is there anyway to integrate the Ehcache monitor within the mapper XML file?  The only documentation I find on setting up the monitor is through a separate ehcache.xml.  If thats the case, can you have an ehcache.xml file to specify the monitor settings and have cache elements defined in the mapper xml files simultaneously?

Thanks!

**Comment by hazendaz** [comment]
@n1zea144 I think this is a bit more of a direct ehcache question rather than integration here.  Correct?
