### ISSUE TITLE
NPE when using EhBlockingCache 

### ISSUE THREAD

**Issue by polopi** [mybatis/ehcache-cache#76]
First I want to thank you for that library, seamless integration to ehcache.

As the documentation suggest we can use EhBlockingCache, I tried to use since I have use case where I have concurrent write to same entry.
Except it fails for every request with NPE.

Looking a the code, it seems that
```
this.cache
```
is never initialized in EhBlockingCache

**Comment by hazendaz** [comment]
@polopi Released versio 1.2.1.  It should be available in central in about 2 hours.
